name: contabilita_familiare
description: App Flutter per la gestione della contabilita familiare.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.5.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^0.69.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
